### ISSUE TITLE
json_to_token_list

### ISSUE THREAD

**Issue by jopiek** [not404/json-arduino#4]
I'm trying the frontpage example with an Arduino / Teensy
- In my case json_to_token_list is faulty: the example will crash on that line.

**Comment by not404** [comment]
This seems to have arisen from the use of malloc() -vs- calloc() to allocate memory. Despite explicitly setting values on allocated structs, using calloc yields more consistent/reliable results.

Refreshed with upstream Jsmn library, and reworked json_arduino wrapper to just use calloc() instead.
